//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_hapticglove : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.hapticglove_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.hapticglove_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.hapticglove_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeft
        {
            get
            {
                return SteamVR_Actions.hapticglove_SkeletonLeft;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeleteonRight
        {
            get
            {
                return SteamVR_Actions.hapticglove_SkeleteonRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.hapticglove_Grip;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.hapticglove_Haptic;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic_Thumb
        {
            get
            {
                return SteamVR_Actions.hapticglove_Haptic_Thumb;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic_Index
        {
            get
            {
                return SteamVR_Actions.hapticglove_Haptic_Index;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic_Middle
        {
            get
            {
                return SteamVR_Actions.hapticglove_Haptic_Middle;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic_Ring
        {
            get
            {
                return SteamVR_Actions.hapticglove_Haptic_Ring;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic_Pinky
        {
            get
            {
                return SteamVR_Actions.hapticglove_Haptic_Pinky;
            }
        }
    }
}
